# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appdate',
        ),
    ]
