# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0005_auto_20180223_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='task',
            new_name='apptask',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='apptime',
        ),
    ]
