# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0007_auto_20180223_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appstatus',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
