# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
