# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0006_auto_20180228_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to='belt_app.User'),
        ),
    ]
