# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_course_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='course_name',
        ),
    ]
