# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0008_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='wish_item',
            new_name='wishlist_item',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='wish_user',
            new_name='wishlist_user',
        ),
    ]
