# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0010_auto_20180228_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='wish_item',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='wish_user',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
