# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20180221_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='blank', max_length=255),
        ),
    ]
