# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='blank', max_length=50)),
                ('username', models.CharField(default='blank', max_length=50)),
                ('password', models.CharField(default='blank', max_length=255)),
                ('date_hired', models.DateField(default='blank')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
