# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_remove_user_date_hired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('trip_start', models.DateTimeField(auto_now_add=True)),
                ('trip_end', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userappts', to='belt_app.User')),
                ('trips_dude', models.ManyToManyField(related_name='tripsdude', to='belt_app.User')),
            ],
        ),
    ]
