# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0005_auto_20180301_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='favorites',
            field=models.ManyToManyField(related_name='wishlist', to='belt_app.User'),
        ),
    ]
